# Generated by the dsdl parser. DO NOT EDIT!

from dsdl.types import *
from enum import Enum, unique


@unique
class MyClassDom(Enum):
    dog = 1
    cat = 2
    fish = 3
    tiger = 4


class ImageClassificationSample(Struct):
    i_list = ListField(ele_type=IntField())
    item_list = ListField(ele_type=ListField(ele_type=IntField()), ordered=True)
    image = ImageField()
    label = LabelField(dom=MyClassDom)
    valid = BoolField()
    val = NumField()
    i_val = IntField()
    p = CoordField()
    date = DateField(fmt="%Y-%m-%d")
    label_list = ListField(ele_type=LabelField(dom=MyClassDom))
