# Generated by the dsdl parser. DO NOT EDIT!

from dsdl.types import *
from enum import Enum, unique


@unique
class MnistImageClassificationClassDom(Enum):
    mnist_0 = 1
    mnist_1 = 2
    mnist_2 = 3
    mnist_3 = 4
    mnist_4 = 5
    mnist_5 = 6
    mnist_6 = 7
    mnist_7 = 8
    mnist_8 = 9
    mnist_9 = 10


class MnistSample(Struct):
    image = ImageField()
    label = LabelField(dom=MnistImageClassificationClassDom, optional=True)
