# Generated by the dsdl parser. DO NOT EDIT!

from dsdl.types import *
from enum import Enum, unique


@unique
class Cifar100ImagesFineLabelClassificationClassDom(Enum):
    apple__fruit_and_vegetables = 1
    aquarium_fish__fish = 2
    baby = 3
    bear = 4
    beaver = 5
    bed = 6
    bee = 7
    beetle = 8
    bicycle = 9
    bottle = 10
    bowl = 11
    boy__people = 12
    bridge = 13
    bus = 14
    butterfly__insects = 15
    camel__large_omnivores_and_herbivores = 16
    can = 17
    castle = 18
    caterpillar = 19
    cattle__large_omnivores_and_herbivores = 20
    chair = 21
    chimpanzee = 22
    clock = 23
    cloud__large_natural_outdoor_scenes = 24
    cockroach = 25
    couch = 26
    crab = 27
    crocodile = 28
    cup__food_containers = 29
    dinosaur__reptiles = 30
    dolphin = 31
    elephant__large_omnivores_and_herbivores = 32
    flatfish = 33
    forest__large_natural_outdoor_scenes = 34
    fox = 35
    girl = 36
    hamster = 37
    house = 38
    kangaroo = 39
    keyboard = 40
    lamp = 41
    lawn_mower = 42
    leopard = 43
    lion = 44
    lizard = 45
    lobster = 46
    man = 47
    maple_tree = 48
    motorcycle = 49
    mountain__large_natural_outdoor_scenes = 50
    mouse = 51
    mushroom__fruit_and_vegetables = 52
    oak_tree = 53
    orange = 54
    orchid = 55
    otter = 56
    palm_tree = 57
    pear = 58
    pickup_truck = 59
    pine_tree = 60
    plain = 61
    plate = 62
    poppy = 63
    porcupine = 64
    possum = 65
    rabbit = 66
    raccoon = 67
    ray = 68
    road = 69
    rocket = 70
    rose = 71
    sea__large_natural_outdoor_scenes = 72
    seal__aquatic_mammals = 73
    shark = 74
    shrew = 75
    skunk = 76
    skyscraper = 77
    snail = 78
    snake = 79
    spider = 80
    squirrel = 81
    streetcar = 82
    sunflower = 83
    sweet_pepper = 84
    table = 85
    tank = 86
    telephone__household_electrical_devices = 87
    television = 88
    tiger = 89
    tractor = 90
    train__vehicles_1 = 91
    trout = 92
    tulip__flowers = 93
    turtle = 94
    wardrobe = 95
    whale = 96
    willow_tree = 97
    wolf = 98
    woman = 99
    worm = 100


@unique
class Cifar100ImagesCoarseLabelClassificationClassDom(Enum):
    aquatic_mammals = 1
    fish = 2
    flowers = 3
    food_containers = 4
    fruit_and_vegetables = 5
    household_electrical_devices = 6
    household_furniture = 7
    insects = 8
    large_carnivores = 9
    large_man_made_outdoor_things = 10
    large_natural_outdoor_scenes = 11
    large_omnivores_and_herbivores = 12
    medium_mammals = 13
    non_insect_invertebrates = 14
    people = 15
    reptiles = 16
    small_mammals = 17
    trees = 18
    vehicles_1 = 19
    vehicles_2 = 20


class Cifar100Sample(Struct):
    image = ImageField()
    label0 = LabelField(dom=Cifar100ImagesFineLabelClassificationClassDom, optional=True)
    label1 = LabelField(dom=Cifar100ImagesCoarseLabelClassificationClassDom, optional=True)
    attributes = DictField(optional=True)
    confidence = NumField(optional=True)
