# Generated by the dsdl parser. DO NOT EDIT!

from dsdl.types import *
from enum import Enum, unique


@unique
class Cifar10ImageClassificationClassDom(Enum):
    airplane = 1
    automobile = 2
    bird = 3
    cat = 4
    deer = 5
    dog = 6
    frog = 7
    horse = 8
    ship = 9
    truck = 10


class AttributeStruct(Struct):
    is_crowd = BoolField()


class TemplateClassification(Struct):
    image = ImageField()
    label = LabelField(dom=Cifar10ImageClassificationClassDom, optional=True)
    confidence = NumField(optional=True)
    attributes = AttributeStruct(optional=True)
