# Generated by the dsdl parser. DO NOT EDIT!

from dsdl.types import *
from enum import Enum, unique


@unique
class Ilsvrc2012ImagesClassificationClassDom(Enum):
    n01968897 = 1
    n01734418 = 2
    n01630670 = 3
    n01498041 = 4
    n02033041 = 5
    n02091244 = 6
    n02094433 = 7
    n01580077 = 8
    n01689811 = 9
    n01986214 = 10


class TemplateClassification(Struct):
    image = ImageField()
    label = LabelField(dom=Ilsvrc2012ImagesClassificationClassDom, optional=True)
    confidence = NumField(optional=True)
    attributes = DictField(optional=True)
