# Generated by the dsdl parser. DO NOT EDIT!

from dsdl.types import *
from enum import Enum, unique


@unique
class MnistImageClassificationClassDom(Enum):
    _0 = 1
    _1 = 2
    _2 = 3
    _3 = 4
    _4 = 5
    _5 = 6
    _6 = 7
    _7 = 8
    _8 = 9
    _9 = 10


class TemplateClassification(Struct):
    image = ImageField()
    label = LabelField(dom=MnistImageClassificationClassDom, optional=True)
    confidence = NumField(optional=True)
    attributes = DictField(optional=True)
