# Generated by the dsdl parser. DO NOT EDIT!

from dsdl.types import *
from enum import Enum, unique


@unique
class VOCClassDom(Enum):
    horse = 1
    person = 2
    bottle = 3
    tvmonitor = 4
    chair = 5
    diningtable = 6
    pottedplant = 7
    aeroplane = 8
    car = 9
    train = 10
    dog = 11
    bicycle = 12
    boat = 13
    cat = 14
    sofa = 15
    bird = 16
    sheep = 17
    motorbike = 18
    bus = 19
    cow = 20


class LocalObjectEntry(Struct):
    bbox = BBoxField()
    label = LabelField(dom=VOCClassDom)
    is_crowd = BoolField()


class ObjectDetectionSample(Struct):
    image = ImageField()
    objects = ListField(ele_type=LocalObjectEntry())
