# Generated by the dsdl parser. DO NOT EDIT!
from dsdl.geometry import ClassDomain
from dsdl.fields import *


class LocalObjectEntry(Struct):
    __params__ = ['cdom']
    __fields__ = {
        "bbox": BBox(),
        "label": Label(dom="$cdom"),
        "is_crowd": Bool(),
    }
    __optional__ = ['label']


ClassDomain(
    name = "COCOClassDom",
    classes = ["person","bicycle","car","motorcycle","airplane","bus","train","truck","boat","traffic light","fire hydrant","stop sign","parking meter","bench","bird","cat","dog","horse","sheep","cow","elephant","bear","zebra","giraffe","backpack","umbrella","handbag","tie","suitcase","frisbee","skis","snowboard","sports ball","kite","baseball bat","baseball glove","skateboard","surfboard","tennis racket","bottle","wine glass","cup","fork","knife","spoon","bowl","banana","apple","sandwich","orange","broccoli","carrot","hot dog","pizza","donut","cake","chair","couch","potted plant","bed","dining table","toilet","tv","laptop","mouse","remote","keyboard","cell phone","microwave","oven","toaster","sink","refrigerator","book","clock","vase","scissors","teddy bear","hair drier","toothbrush",],
)


class ObjectDetectionSample(Struct):
    __params__ = ['cdom']
    __fields__ = {
        "image": Image(),
        "objects": List(etype=LocalObjectEntry(cdom="$cdom")),
    }

