import click
from abc import ABC, abstractmethod
from yaml import load as yaml_load
from .exception import StructHasDefinedError, DefineSyntaxError
import networkx as nx

try:
    from yaml import CSafeLoader as YAMLSafeLoader
except ImportError:
    from yaml import SafeLoader as YAMLSafeLoader


class Parser(ABC):
    @abstractmethod
    def parse(self, input_file):
        pass

    @abstractmethod
    def generate(self, output_file):
        pass

    def process(self, input_file, output_file):
        self.parse(input_file)
        self.generate(output_file)


class DSDLParser(Parser):
    def __init__(self):
        self.define_map = dict()

    def parse(self, input_file):
        with open(input_file, "r") as f:
            desc = yaml_load(f, Loader=YAMLSafeLoader)

        for define in desc["defs"].items():
            define_name = define[0]
            define_type = define[1]["$def"]
            if not define_name.isidentifier():
                continue
            if define_name in self.define_map:
                raise StructHasDefinedError(f"{define_name} has defined.")

            define_info = {"name": define_name}
            if define_type == "struct":
                define_info["type"] = "struct"
                define_info["field_list"] = []
                for raw_field in define[1]["$fields"].items():
                    if not raw_field[0].isidentifier():
                        continue
                    define_info["field_list"].append(
                        {
                            "name": raw_field[0],
                            "type": self.parse_struct_field(raw_field[1]),
                        }
                    )

            if define_type == "class_domain":
                define_info["type"] = "class_domain"
                define_info["class_list"] = []
                for class_name in define[1]["classes"]:
                    if not class_name.isidentifier():
                        continue
                    define_info["class_list"].append(
                        {
                            "name": class_name,
                        }
                    )

            self.define_map[define_info["name"]] = define_info

    def generate(self, output_file):
        # WIP: check define cycles.
        define_graph = nx.DiGraph()
        define_graph.add_nodes_from(self.define_map.keys())
        for key, val in self.define_map.items():
            if val["type"] != "struct":
                continue
            for field in val["field_list"]:
                for k in self.define_map.keys():
                    if k in field["type"]:
                        define_graph.add_edge(k, key)
        if not nx.is_directed_acyclic_graph(define_graph):
            raise "define cycle found."

        with open(output_file, "w") as of:
            print("# Generated by the dsdl parser. DO NOT EDIT!\n", file=of)
            print("from dsdl.types import *\nfrom enum import Enum\n\n", file=of)
            ordered_keys = list(nx.topological_sort(define_graph))
            for idx, key in enumerate(ordered_keys):
                val = self.define_map[key]
                if val["type"] == "struct":
                    print(f"class {key}(Struct):", file=of)
                    for field in val["field_list"]:
                        print(f"""    {field["name"]} = {field["type"]}""", file=of)
                if val["type"] == "class_domain":
                    print(f"class {key}(Enum):", file=of)
                    for item in val["class_list"]:
                        class_name = item["name"]
                        print(f'''    {class_name.upper()} = "{class_name}"''', file=of)
                if idx != len(ordered_keys) - 1:
                    print("\n", file=of)

    @staticmethod
    def parse_struct_field_with_params(raw: str) -> str:
        def sanitize_dom(val: str) -> str:
            if not val.isidentifier():
                raise DefineSyntaxError(f"invalid dom: {val}")
            return val

        def sanitize_fmt(val: str) -> str:
            val = val.strip("\"'")
            return f'"{val}"'

        field_map = {
            "Label": {"dom": sanitize_dom},
            "Date": {"fmt": sanitize_fmt},
            "Time": {"fmt": sanitize_fmt},
        }
        field_type = ""
        for k in field_map.keys():
            if raw.startswith(k):
                field_type = k
        if field_type == "":
            raise "Unknown field"

        raw = raw.replace(f"{field_type}[", "").replace("]", "")
        param_list = raw.split(",")
        valid_param_list = []
        for param in param_list:
            parts = param.split("=")
            if len(parts) != 2:
                continue
            if parts[0] not in field_map[field_type]:
                continue
            sanitized = field_map[field_type][parts[0]](parts[1])
            valid_param_list.append(f"{parts[0]}={sanitized}")
        return field_type + "Field(" + ",".join(valid_param_list) + ")"

    @staticmethod
    def parse_struct_field(raw_field_type: str) -> str:
        if raw_field_type in [
            "Bool",
            "Num",
            "Int",
            "Str",
            "Coord",
            "Coord3D",
            "Interval",
            "BBox",
            "Polygon",
            "Image",
        ]:
            return raw_field_type + "Field()"
        return DSDLParser.parse_struct_field_with_params(raw_field_type)


@click.command()
@click.option(
    "-y",
    "--yaml",
    "dsdl_yaml",
    type=str,
    required=True,
)
def parse(dsdl_yaml):
    output_file = dsdl_yaml.replace(".yaml", ".py")
    dsdl_parser = DSDLParser()
    dsdl_parser.process(dsdl_yaml, output_file)
